### ISSUE TITLE
Please give feedback

### ISSUE THREAD

**Issue by bobbyroberts99** [bobbyroberts99/Signal-Cartel#7]
I'm relatively inexperienced at webdev and would be thankful for feedback and tips. This site works but almost certainly could do with some refactoring. This is a learning experience and I welcome input.

* What works?
* What doesn't work?
* What can we do about it?

Feel free to add to existing or create new issues. And if the benefit of this site isn't worth the effort required to take it live, it's OK. I had fun doing it, learned something and refreshed my memory to boot.

**Comment by Mynxee** [comment]
I am really clueless about github and have deadlines this week in RL that limit how much time I have to respond to this. But good to learn something new and I'll enjoy the collaboration ... just be patient with my availability.

**Comment by bobbyroberts99** [comment]
Take your time. Actually, although I guess I sound a tad needy here, I'm just trying to make sure you both feel comfortable telling me what you really think. One thing I really like about open-source collaboration is that people can just do what they think makes sense, and then the people they do it for can accept all, part or none of the gift after discussing and revising together. It's very flexible.

I'll keep working on the problems I've identified and any you point out. At this point, it's probably easiest for Johnny to merge what he wants into the eve-scout website. In asking for feedback, I was mostly hoping that if he can see ways to improve the code (make it DRYer/make more sense), then I'd love to have his feedback.

If you want, I can show you how to change links/text from Github. We could mumble it up or do a screen share whenever you have time. I'm in no hurry.
